USE ETL_DB;
GO

CREATE TABLE ETL_DATA (
    activityName NVARCHAR(255),
    activityRunEnd DATETIME,
    activityRunId NVARCHAR(255),
    activityRunStart NVARCHAR(255),
    activityType NVARCHAR(255),
    durationInMs FLOAT,
    pipelineName NVARCHAR(255),
    pipelineRunId NVARCHAR(255),
    status NVARCHAR(255),
    billableDuration FLOAT,
    billable_meterType NVARCHAR(255),
    billable_unit NVARCHAR(255),
    totalBillableDuration FLOAT,
    totalBillable_meterType NVARCHAR(255),
    totalBillable_unit NVARCHAR(255),
    copyDuration FLOAT,
    dataConsistencyVerification NVARCHAR(255),
    dataRead FLOAT,
    dataWritten FLOAT,
    durationInQueue FLOAT,
    effectiveIntegrationRuntime NVARCHAR(255),
    queuingDuration FLOAT,
    timeToFirstByte FLOAT,
    transferDuration FLOAT,
    totalDuration FLOAT,
    interimDataWritten FLOAT,
    interimRowsCopied FLOAT,
    queueStatus NVARCHAR(255),
    queueDuration FLOAT,
    integrationRuntime_name NVARCHAR(255),
    integrationRuntime_type NVARCHAR(255),
    integrationRuntime_location NVARCHAR(255),
    integrationRuntimeName NVARCHAR(255),
    rowsCopied FLOAT,
    rowsRead FLOAT,
    sinkPeakConnections FLOAT,
    sourcePeakConnections FLOAT,
    throughput FLOAT
);
